site: TAJD
url: https://tajd.github.io
title: TAJD
description: Thomas Dickson 
future: true

permalink: pretty

paginate:            1000
paginate_path:       "/page:num/"
baseurl:             ""
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at

collections:
  technical_notes:
    output: true
    permalink: technical_notes/:slug
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
      
  - scope:
      path: "assets/images"
    values:
      image: true

# Optional. The default date format, used if none is specified in the tag.
last-modified-at:
  date-format: '%d %b %y'